<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>tb.txt</string>
	</array>
	<key>name</key>
	<string>TurboBadger Node Markup</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Comments</string>
			<key>match</key>
			<string>^\s*\#.*$</string>
			<key>name</key>
			<string>comment.line.number-sign</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^\s*[A-Z]{1,}|^)(\w+).?([\w\.\-\_]+)?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.class</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.modifier</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Type names</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
					</dict>
					<key>match</key>
					<string>([\w\-]+):\s*([^,$]+)*</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\"</string>
			<key>comment</key>
			<string>Quoted strings</string>
			<key>end</key>
			<string>\"</string>
			<key>name</key>
			<string>string.quoted</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\\"</string>
					<key>name</key>
					<string>constant.character.escape.string</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*([\w\-]+):</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Structure with values in a single line</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.unquoted</string>
						</dict>
					</dict>
					<key>match</key>
					<string>([\w\-]+):\s*([^,$]*)</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Property name without value</string>
			<key>match</key>
			<string>^\s*([\w\-]+)$</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.other</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Hexadecimal colors</string>
			<key>match</key>
			<string>^\s*([\w\-]+)\s+(#[0-9a-fA-F]{3,6})$</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Number w/ optional unit type</string>
			<key>match</key>
			<string>^\s*([\w\-]+)\s+([\-\.\d]+(px|pt|))$</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Multiple numbers w/o unit type</string>
			<key>match</key>
			<string>^\s*([\w\-]+)\s+([\-\.\d ]+)$</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Translated string</string>
			<key>match</key>
			<string>^\s*([\w\-]+)\s+(\@.*)$</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.unquoted</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Regular value</string>
			<key>match</key>
			<string>^\s*([\w\-]+)\s+(.*)$</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.turbobadger</string>
	<key>uuid</key>
	<string>aa04f52c-a770-4ca8-833c-341c4d67633d</string>
</dict>
</plist>
